import Head from "next/head";
import styles from "../styles/Home.module.css";

export default function Home() {
	return (
		<div className={styles.container}>
			<Head>
				<title>{`Jason Chen`}</title>
				<meta name="Portfolio website for Jason Chen" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico?" />
			</Head>
		</div>
	);
}
